services:
  traefik:
    image: traefik:1.7-alpine
    command:
      - --docker.domain=${DOMAIN:-lvh.me}
      - --api.dashboard
    labels:
      - "traefik.frontend.rule=Host:traefik.${DOMAIN:-lvh.me}"
      - "traefik.port=8080"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  lunch:
    image: web:v7
    ports:
    - 80
    environment:
      - TITLE=${TITLE:-Lazy DEV}
      - COLOR=${COLOR:-gray}
      - BODY=${BODY:- Please set TITLE/COLOR/BODY in .env file ;)}
  backend:
    image: web:v7
    build:
      context: .
      tags:
      - lalyos/web
      - ttl.sh/web
    environment:
      - TITLE=${BACKEND_TITLE:-Backend [DEV]}
      - COLOR=${BACKEND_COLOR:-gray}
      - BODY=${BACKEND_BODY:-hint .env}
    ports:
      - 80
  frontend:
    image: web:v7
    environment:
      - TITLE=${FRONTEND_TITLE:-FRONTEND [DEV]}
      - COLOR=${FRONTEND_COLOR:-gray}
      - BODY=${FRONTEND_BODY:-hint .env}
    ports:
      - 80