services:
  traefik:
    image: traefik:1.7-alpine
    command:
      - --docker.domain=lvh.me
      - --api.dashboard
    labels:
      - "traefik.frontend.rule=Host:traefik.lvh.me"
      - "traefik.port=8080"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  lunch:
    image: web:v7
    environment:
      - TITLE=lunch for lalyos
      - COLOR=hotpink
      - VIRTUAL_HOST=lunch.lvh.me
  backend:
    image: web:v7
    build:
      context: .
      tags:
      - lalyos/web
      - ttl.sh/web
    environment:
      - TITLE=Dinner [dev]
      - COLOR=yellow
      - VIRTUAL_HOST=backend.lvh.me
    ports:
      - 80
  frontend:
    image: web:v7
    environment:
      - TITLE=FRONT [dev]
      - COLOR=yellow
      - BODY=<iframe src="https://giphy.com/embed/5t235Nf4wo3rhLSMVy" width="480" height="333" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/garfield-cat-food-5t235Nf4wo3rhLSMVy">via GIPHY</a></p>
      - VIRTUAL_HOST=backend.lvh.me
    ports:
      - 80